name: kalmora
description: "My Mobile Application"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0
  record: ^6.0.0
  audioplayers: ^6.4.0

  image_picker: ^1.0.4

  permission_handler: ^11.4.0
  connectivity_plus: ^6.1.3
  video_player: ^2.8.2
  cupertino_icons: ^1.0.8

  firebase_core: ^3.13.0
  firebase_storage: ^12.4.4
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.6
  firebase_app_check: ^0.3.2+5

  get: ^4.6.5      # Add this if missing
  uuid: ^4.5.1
  shared_preferences: ^2.2.2
  speech_to_text: ^7.0.0
  provider: ^6.1.4
  intl: ^0.20.2

  # Audio recording
  flutter_sound: ^9.28.0
  path_provider: ^2.1.5
  flutter_recorder: ^1.1.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/kalmora_logo.mp4
    - assets/images/

  fonts:
    - family: Cinzel
      fonts:
      - asset: assets/fonts/Cinzel/static/Cinzel-Regular.ttf
      - asset: assets/fonts/Cinzel/static/Cinzel-Bold.ttf
        weight: 700

    - family: CinzelDecorative
      fonts:
        - asset: assets/fonts/Cinzel_Decorative/CinzelDecorative-Regular.ttf
        - asset: assets/fonts/Cinzel_Decorative/CinzelDecorative-Bold.ttf
          weight: 700